In [1]:
import numpy as np
from sklearn import datasets
from sklearn import metrics
from sklearn import preprocessing
from sklearn import model_selection
from NeuralNetwork import NeuralNetwork
import common

In [2]:
digits = datasets.load_digits()
X = digits.data
y = digits.target
X -= X.min()
X /= X.max()

In [3]:
nn = NeuralNetwork([64, 100, 10], common.logistic, common.logistic_derivative)

In [4]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y)
labels_train = preprocessing.LabelBinarizer().fit_transform(y_train)
labels_test = preprocessing.LabelBinarizer().fit_transform(y_test)

In [5]:
nn.fit(X_train, labels_train, epochs=3000)

In [8]:

predictions = nn.predict(X_test)


In [9]:
print(metrics.confusion_matrix(y_test, predictions))

[[48  0  0  0  0  0  0  0  0  0]
 [ 0 32  1  0  0  1  1  0  0  2]
 [ 0  5 46  0  0  0  0  0  0  0]
 [ 0  0  0 47  0  0  0  4  0  3]
 [ 0  0  0  0 46  0  0  1  0  0]
 [ 0  0  0  0  0 38  1  0  0  2]
 [ 0  2  0  0  0  0 48  0  1  0]
 [ 0  0  0  0  1  2  0 43  0  0]
 [ 0  7  0  0  0  0  0  0 24  4]
 [ 0  0  0  0  0  1  0  0  0 39]]


In [10]:
print(metrics.classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        48
           1       0.70      0.86      0.77        37
           2       0.98      0.90      0.94        51
           3       1.00      0.87      0.93        54
           4       0.98      0.98      0.98        47
           5       0.90      0.93      0.92        41
           6       0.96      0.94      0.95        51
           7       0.90      0.93      0.91        46
           8       0.96      0.69      0.80        35
           9       0.78      0.97      0.87        40

   micro avg       0.91      0.91      0.91       450
   macro avg       0.92      0.91      0.91       450
weighted avg       0.92      0.91      0.91       450

