In [1]:
import numpy as np
from sklearn import datasets
from sklearn import metrics
from sklearn import preprocessing
from sklearn import model_selection
from NeuralNetwork import NeuralNetwork
import common

In [4]:
digits = datasets.load_digits()
X = digits.data
y = digits.target
X -= X.min()
X /= X.max()

In [5]:
nn = NeuralNetwork([64, 100, 10], common.logistic, common.logistic_derivative)

In [6]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y)
labels_train = preprocessing.LabelBinarizer().fit_transform(y_train)
labels_test = preprocessing.LabelBinarizer().fit_transform(y_test)

In [7]:
nn.fit(X_train, labels_train, epochs=3000)

In [14]:
predictions = []
for i in range(X_test.shape[0]):
    o = nn.predict(X_test[i])
    predictions.append(np.argmax(o))

X_test shape: (450, 64)
[0.     0.     0.     0.875  1.     0.9375 0.6875 0.     0.     0.
 0.125  1.     1.     1.     0.625  0.     0.     0.     0.25   1.
 1.     1.     0.25   0.     0.     0.     0.75   1.     1.     0.75
 0.     0.     0.     0.     0.75   1.     1.     0.375  0.     0.
 0.     0.     0.875  1.     1.     0.375  0.     0.     0.     0.
 0.6875 1.     0.9375 0.125  0.     0.     0.     0.     0.0625 0.9375
 0.9375 0.0625 0.     0.    ]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
predict result: [4.63531178e-04 7.57047044e-01 3.56711019e-03 6.63028773e-03
 2.87161598e-02 1.82666542e-03 1.16300648e-03 1.20591151e-01
 5.24124140e-01 8.53711637e-03], shape: (10,)
[0.     0.     0.     0.5625 0.875  0.0625 0.     0.     0.     0.
 0.125  1.     0.5    0.     0.     0.     0.     0.     0.75   0.875
 0.0625 0.     0. 

[0.     0.     0.5625 1.     1.     0.8125 0.125  0.     0.     0.125
 0.9375 0.125  0.1875 0.1875 0.     0.     0.     0.4375 0.5625 0.
 0.0625 0.25   0.     0.     0.     0.5    0.75   0.4375 0.8125 0.875
 0.4375 0.     0.     0.375  1.     0.5    0.     0.3125 0.5    0.
 0.     0.0625 0.1875 0.     0.     0.5625 0.375  0.     0.     0.
 0.1875 0.25   0.0625 0.9375 0.     0.     0.     0.     0.4375 1.
 0.75   0.4375 0.     0.    ]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
predict result: [7.43010257e-02 3.96040487e-04 3.82715335e-04 1.08089716e-02
 7.80911404e-04 7.77346051e-01 1.01502453e-03 8.94923113e-03
 4.87618676e-03 1.80301348e-01], shape: (10,)
[0.     0.     0.5625 1.     1.     0.4375 0.     0.     0.     0.8125
 0.9375 0.5625 0.75   0.9375 0.     0.     0.     0.3125 0.25   0.
 0.8125 0.8125 0.     0.     0.     0.   

predict result: [9.62646093e-01 6.78017754e-04 3.82994484e-03 2.87651264e-04
 2.68662463e-02 4.12351491e-03 8.67411186e-03 8.92538232e-04
 2.93940244e-03 2.94352877e-02], shape: (10,)
[0.     0.     0.6875 0.9375 0.25   0.     0.     0.     0.     0.3125
 1.     0.9375 0.9375 0.     0.     0.     0.     0.     0.875  0.6875
 1.     0.125  0.     0.     0.     0.     0.     0.25   1.     0.3125
 0.     0.     0.     0.     0.     0.25   1.     0.375  0.     0.
 0.     0.     0.     0.4375 1.     0.625  0.1875 0.     0.     0.
 0.6875 1.     1.     1.     1.     0.375  0.     0.     0.6875 1.
 0.625  0.3125 0.8125 0.375 ]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
predict result: [4.60511270e-04 1.54780527e-01 8.38340066e-01 8.99706695e-02
 1.84349963e-04 1.98893552e-02 3.91022789e-03 1.26066249e-03
 9.95975174e-03 1.21433515e-03], sh

predict result: [0.00287997 0.11694649 0.01201877 0.00085462 0.00425212 0.00213735
 0.03636405 0.00531    0.76995437 0.00603473], shape: (10,)
[0.     0.     0.     0.1875 1.     0.5    0.     0.     0.     0.
 0.     0.6875 1.     0.5625 0.     0.     0.     0.1875 0.75   1.
 1.     0.5    0.     0.     0.     0.8125 1.     0.5625 1.     0.5
 0.     0.     0.     0.0625 0.125  0.     1.     0.5    0.     0.
 0.     0.     0.     0.125  1.     0.25   0.     0.     0.     0.
 0.     0.125  1.     0.375  0.     0.     0.     0.     0.     0.0625
 1.     0.5625 0.     0.    ]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
predict result: [1.15328293e-04 9.47133775e-01 3.83467031e-04 8.10092618e-03
 6.48037454e-02 1.52605585e-02 1.93388929e-04 1.95142159e-03
 9.09142173e-03 2.75192331e-02], shape: (10,)
[0.     0.     0.     0.3125 0.6875 0

[0.     0.     0.125  0.5    0.4375 0.     0.     0.     0.     0.
 0.375  0.9375 1.     0.125  0.     0.     0.     0.375  0.9375 0.6875
 1.     0.25   0.     0.     0.     0.3125 1.     0.625  1.     0.0625
 0.     0.     0.     0.125  0.9375 1.     0.8125 0.     0.     0.
 0.     0.     0.125  1.     0.75   0.5625 0.1875 0.     0.     0.
 0.25   0.875  0.     0.75   0.875  0.0625 0.     0.     0.0625 0.75
 0.625  0.4375 0.     0.    ]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
predict result: [2.55910481e-04 6.92054540e-01 5.50158128e-03 9.66957962e-04
 2.17273632e-02 1.73208279e-02 1.00519373e-01 9.48892818e-04
 1.13591850e-01 3.00751364e-03], shape: (10,)
[0.     0.     0.375  0.875  0.625  0.     0.     0.     0.     0.375
 1.     0.875  1.     0.     0.     0.     0.     0.3125 0.625  0.6875
 1.     0.     0.     0.     0.   

predict result: [2.42291571e-03 2.22695738e-02 6.39599843e-01 1.26203882e-01
 8.88684138e-05 1.31799817e-02 1.11264193e-03 1.02125682e-02
 8.01292547e-02 1.95151806e-03], shape: (10,)
[0.     0.     0.125  0.8125 0.5    0.375  0.     0.     0.     0.
 0.4375 0.875  0.875  1.     0.     0.     0.     0.     0.4375 0.5625
 0.1875 1.     0.25   0.     0.     0.     0.3125 0.875  0.9375 1.
 0.25   0.     0.     0.     0.     0.1875 0.125  0.8125 0.3125 0.
 0.     0.     0.1875 0.     0.     0.75   0.375  0.     0.     0.0625
 0.75   0.375  0.     0.6875 0.4375 0.     0.     0.     0.1875 0.75
 1.     1.     0.0625 0.    ]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
predict result: [4.41081920e-02 2.23153227e-02 2.87485687e-03 1.07372389e-01
 1.64368454e-04 1.63687757e-03 2.73211893e-04 5.11647402e-03
 7.63983488e-02 6.62606848e-01], shap

predict result: [3.99334132e-02 1.22852279e-02 2.95791194e-05 1.15125187e-05
 9.78022136e-01 2.51079584e-02 6.42234140e-03 4.35457421e-02
 5.18287402e-04 1.25009714e-03], shape: (10,)
[0.     0.     0.     0.625  0.8125 0.1875 0.     0.     0.     0.
 0.5    1.     0.875  0.75   0.     0.     0.     0.1875 1.     0.8125
 0.     0.875  0.0625 0.     0.     0.3125 1.     0.375  0.     0.875
 0.3125 0.     0.     0.375  1.     0.     0.     0.9375 0.25   0.
 0.     0.125  0.8125 0.0625 0.3125 1.     0.25   0.     0.     0.
 0.625  1.     1.     0.875  0.0625 0.     0.     0.     0.125  0.6875
 0.8125 0.375  0.     0.    ]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
predict result: [9.29504161e-01 2.47386642e-03 6.36733079e-04 2.56810421e-04
 1.08834886e-01 1.06275479e-02 1.37999247e-02 1.11386003e-03
 1.19694347e-02 3.06338135e-02], sha

predict result: [3.27717038e-04 8.59317258e-01 4.64441097e-02 8.26531013e-03
 8.49766657e-03 8.41904830e-03 4.18347284e-02 1.42880665e-03
 4.02270915e-01 2.18962347e-03], shape: (10,)
[0.     0.     0.5625 1.     1.     1.     0.4375 0.     0.     0.1875
 1.     0.6875 0.25   0.25   0.0625 0.     0.     0.375  1.     0.0625
 0.     0.     0.     0.     0.     0.5625 1.     0.5625 0.25   0.
 0.     0.     0.     0.     0.375  0.625  1.     0.5    0.     0.
 0.     0.     0.125  0.     0.5    0.875  0.     0.     0.     0.
 0.8125 0.4375 0.5    0.875  0.     0.     0.     0.     0.625  1.
 1.     0.25   0.     0.    ]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
predict result: [8.83543994e-03 1.51753503e-03 3.10679052e-03 2.39927243e-02
 3.74156048e-04 9.51445411e-01 1.68476886e-02 1.48296619e-03
 3.74836291e-02 6.30702705e-03], shape:

In [15]:
print(metrics.confusion_matrix(y_test, predictions))

[[43  0  0  0  1  0  0  0  0  0]
 [ 0 39  3  0  0  1  2  0  3  1]
 [ 0  1 35  1  0  0  0  1  0  1]
 [ 0  1  0 43  0  2  0  2  3  0]
 [ 0  0  0  0 47  0  0  1  0  2]
 [ 0  0  0  0  0 36  0  0  0  6]
 [ 1  0  0  0  0  0 54  0  0  0]
 [ 0  0  0  0  1  0  0 32  1  5]
 [ 0  3  0  0  0  2  1  0 42  0]
 [ 0  0  0  1  0  0  0  0  0 32]]


In [14]:
print(metrics.classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98        44
           1       0.89      0.80      0.84        49
           2       0.92      0.90      0.91        39
           3       0.96      0.84      0.90        51
           4       0.96      0.94      0.95        50
           5       0.88      0.86      0.87        42
           6       0.95      0.98      0.96        55
           7       0.89      0.82      0.85        39
           8       0.86      0.88      0.87        48
           9       0.68      0.97      0.80        33

   micro avg       0.90      0.90      0.90       450
   macro avg       0.90      0.90      0.89       450
weighted avg       0.90      0.90      0.90       450

