In [6]:
import numpy as np
from sklearn import datasets
from sklearn import metrics
from sklearn import preprocessing
from sklearn import model_selection
from NeuralNetwork import NeuralNetwork
import common

In [7]:
digits = sk.datasets.load_digits()
X = digits.data
y = digits.target
X -= X.min()
X /= X.max()

In [8]:
nn = NeuralNetwork([64, 100, 10], common.logistic, common.logistic_derivative)

In [9]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y)
labels_train = preprocessing.LabelBinarizer().fit_transform(y_train)
labels_test = preprocessing.LabelBinarizer().fit_transform(y_test)

In [10]:
nn.fit(X_train, labels_train, epochs=3000)

In [11]:
predictions = []
for i in range(X_test.shape[0]):
    o = nn.predict(X_test[i])
    predictions.append(np.argmax(o))

In [15]:
print(metrics.confusion_matrix(y_test, predictions))

[[43  0  0  0  1  0  0  0  0  0]
 [ 0 39  3  0  0  1  2  0  3  1]
 [ 0  1 35  1  0  0  0  1  0  1]
 [ 0  1  0 43  0  2  0  2  3  0]
 [ 0  0  0  0 47  0  0  1  0  2]
 [ 0  0  0  0  0 36  0  0  0  6]
 [ 1  0  0  0  0  0 54  0  0  0]
 [ 0  0  0  0  1  0  0 32  1  5]
 [ 0  3  0  0  0  2  1  0 42  0]
 [ 0  0  0  1  0  0  0  0  0 32]]


In [14]:
print(metrics.classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98        44
           1       0.89      0.80      0.84        49
           2       0.92      0.90      0.91        39
           3       0.96      0.84      0.90        51
           4       0.96      0.94      0.95        50
           5       0.88      0.86      0.87        42
           6       0.95      0.98      0.96        55
           7       0.89      0.82      0.85        39
           8       0.86      0.88      0.87        48
           9       0.68      0.97      0.80        33

   micro avg       0.90      0.90      0.90       450
   macro avg       0.90      0.90      0.89       450
weighted avg       0.90      0.90      0.90       450

